fixtures:
  repositories:
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref:  '4.6.0'
    archive:
      repo: 'https://github.com/camptocamp/puppet-archive.git'
  symlinks:
    oauth2_proxy: "#{source_dir}"
