sudo: false
language: ruby
bundler_args: --without beaker
rvm:
  - '2.2'
  - '2.3.1'
  - '2.4'
env:
  - PUPPET_GEM_VERSION="~> 3.7"
  - PUPPET_GEM_VERSION="~> 4.0"
matrix:
  include:
    - rvm: '2.2'
      sudo: required
      services: docker
      env:
        - PUPPET_GEM_VERSION="~> 4.0"
        - BEAKER_set="centos-7-docker"
      script: bundle exec rake beaker
      bundler_args: --without development
    - rvm: '2.2'
      sudo: required
      services: docker
      env:
        - PUPPET_GEM_VERSION="~> 4.0"
        - BEAKER_set="ubuntu-14-docker"
      script: bundle exec rake beaker
      bundler_args: --without development
    - rvm: '2.3.1'
      sudo: required
      services: docker
      env:
        - PUPPET_GEM_VERSION="~> 4.0"
        - BEAKER_set="centos-7-docker"
      script: bundle exec rake beaker
      bundler_args: --without development
    - rvm: '2.3.1'
      sudo: required
      services: docker
      env:
        - PUPPET_GEM_VERSION="~> 4.0"
        - BEAKER_set="ubuntu-14-docker"
      script: bundle exec rake beaker
      bundler_args: --without development
  exclude:
    - rvm: '2.2'
      env: PUPPET_GEM_VERSION="~> 3.7"
    - rvm: '2.3.1'
      env: PUPPET_GEM_VERSION="~> 3.7"
  fast_finish: true
notifications:
  email: false
